import { gql } from 'graphql-tag';
import { resolve, extname } from 'path';
import { readFileSync, Dirent, writeFileSync, readdirSync } from 'fs';

import { GraphQLSchemaModule } from 'apollo-server';
import { buildSubgraphSchema, printSubgraphSchema } from '@apollo/subgraph';

const graphqlFolder = resolve(__dirname, '..', 'graphql');

/**
 * Combines all defined typeDefs and resolvers
 * from files in the *graphql* folder into a single subgraph schema.
 * @returns `GraphQLSchema`
 */
export async function generateSubgraphSchema() {
  const schemaModules = [];
  const schemaFiles = readdirSync(graphqlFolder, {
    withFileTypes: true,
  }).filter((file) => {
    const extension = extname(file.name).toLowerCase();

    return extension === '.ts' || extension === '.graphql';
  });

  for (const schemaFile of schemaFiles) {
    const loadedModel = await loadModule(schemaFile);
    if (loadedModel) {
      schemaModules.push(loadedModel);
    }
  }

  return buildSubgraphSchema(schemaModules as any);
}

export async function writeSchema() {
  const schema = await generateSubgraphSchema();
  const generatedString = `# This file was autogenerated for CI purposes
  
# See https://github.com/apollographql/subgraph-template-typescript-apollo-server/blob/main/src/utils/schema.ts
`;
  writeFileSync(
    resolve(__dirname, '..', '..', 'generated-schema.graphql'),
    `${generatedString}${printSubgraphSchema(schema)}`,
    {
      encoding: 'utf-8',
    },
  );
}

/**
 * Load a set of typeDefs and resolvers.
 * @param module - The Dirent of the folder
 * @returns { typeDefs, resolvers? }
 */
export async function loadModule(
  module: Dirent,
): Promise<GraphQLSchemaModule | undefined> {
  const moduleName = module.name?.split('.')?.shift();
  if (moduleName) {
    console.log(`Loading GraphQLSchemaModule: ${module.name}`);

    const ext = extname(module.name).toLowerCase();
    if (ext === '.graphql') {
      const path = resolve(graphqlFolder, module.name);
      const typeDefs = gql(
        readFileSync(path, {
          encoding: 'utf-8',
        }),
      );

      try {
        const { resolvers } = await import(resolve(graphqlFolder, moduleName));

        return { typeDefs, resolvers };
      } catch (err) {
        console.log(
          `No resolvers loaded for ${module.name}, schema will be mocked`,
        );
      }

      return { typeDefs };
    } else if (ext === '.ts') {
      const { typeDefs, resolvers } = await import(
        resolve(graphqlFolder, moduleName)
      );
      if (!typeDefs) return undefined;
      return { typeDefs, resolvers };
    }
  }
  return undefined;
}
